### ISSUE TITLE
Adicionar validação ao cadastrar nova cidade

### ISSUE THREAD

**Issue by Gabriel-Benito** [GuilhermeCupertino/trabalhoGCS#15]
Percebi que ao cadastrar novas cidades não há validação para verificar se a cidade digitada realmente existe. Dessa forma, quando cadastramos uma suposta cidade não existente, ao tentar buscá-la no mapa não obtemos sucesso. Tal falta de funcionalidade pode levar a futuros erros e bugs afetando a usabalidade e solidez da aplicação.

Sugiro adicionar uma camada de validação no campo "cidade" ao realizar o cadastro antes de concluir o salvamento no banco de dados, visando solucionar a problemática supracitada.

**Comment by ghost** [comment]
Essa issue foi resolvida sem muitos problemas. Implementamos a camada de validação no campo "cidade" conforme foi sugerido, essa validação verifica a existência da cidade com a API do Google Places antes de concluir o salvamento no banco de dados.

**Comment by GuilhermeCupertino** [comment]
A issue foi resolvida. Com a adição da funcionalidade, agora haverá a validação das cidades. Não houve problemas na resolução.
