### ISSUE TITLE
Prevenção de cadastro de cidades com estados inexistentes

### ISSUE THREAD

**Issue by GuilhermeCupertino** [GuilhermeCupertino/trabalhoGCS#19]
Nosso sistema permite que os usuários cadastrem cidades sem verificar se o estado inserido de fato existe. Isso pode causar complicações, já que os dados podem ficar incoerentes.

Para solucionar esse problema, será necessário implementar uma forma de inserir os estados em um Spinner:

- Criar um Spinner e adicionar todos os estados como opções desse Spinner.
- Implementar o Spinner, e sua lógica por trás. Além de alterar o banco de dados para entrar em conformidade.
- Adicionar o Spinner no Layout e fazer as alterações necessárias para se tornar funcional.

**Comment by Eissenv** [comment]
Olá Guilherme, estou considerando o fato do nosso sistema permitir que o usuário insira qualquer cidade/estado de qualquer país no sistema. Para corrigir esse bug usando Spinners, acredito que precisaremos de dois Spinners: um para selecionar o país e outro para selecionar o estado. Dessa forma, os estados exibidos no segundo Spinner serão filtrados de acordo com o país selecionado anteriormente, o que proporcionará uma organização melhor.

Além disso, seria interessante pensarmos em integrar uma API geográfica para validar os estados disponíveis, em vez de adicioná-los manualmente. Existem várias APIs públicas que oferecem essa funcionalidade. Aqui estão algumas opções que podemos avaliar:

API IBGE de Consulta de Localidades (Brasil): Esta API permite consultar estados brasileiros e suas respectivas cidades. É excelente para operações dentro do Brasil, mas limitada a este país.

API Geonames (Internacional): Fornecerá informações geográficas de todo o mundo, incluindo estados e cidades de vários países. 

Se precisar de alguma ajuda, pode entrar em contato.

**Comment by ghost** [comment]
Olá Guilherme, estou considerando o fato do nosso sistema permitir que o usuário insira qualquer cidade/estado de qualquer país no sistema. Para corrigir esse bug usando Spinners, acredito que precisaremos de dois Spinners: um para selecionar o país e outro para selecionar o estado. Dessa forma, os estados exibidos no segundo Spinner serão filtrados de acordo com o país selecionado anteriormente, o que proporcionará uma organização melhor.

Além disso, seria interessante pensarmos em integrar uma API geográfica para validar os estados disponíveis, em vez de adicioná-los manualmente. Existem várias APIs públicas que oferecem essa funcionalidade. Aqui estão algumas opções que podemos avaliar:

API IBGE de Consulta de Localidades (Brasil): Esta API permite consultar estados brasileiros e suas respectivas cidades. É excelente para operações dentro do Brasil, mas limitada a este país.

API Geonames (Internacional): Fornecerá informações geográficas de todo o mundo, incluindo estados e cidades de vários países.

Se precisar de alguma ajuda, pode entrar em contato.

**Comment by jecelen** [comment]
Como aqui se trata da adição de uma função de validação de estados, achei melhor considerarmos uma feature e não um bug.

**Comment by Gabriel-Benito** [comment]
Recomendo, ao adicionar essa funcionalidade relacionada aos estados, deixar claro que são somente estados brasileiros para não fugir do escopo da aplicação.
