### ISSUE TITLE
Ao usar a funcionalidade "buscar endereço" o aplicativo fecha imediatamente.

### ISSUE THREAD

**Issue by Gabriel-Benito** [GuilhermeCupertino/trabalhoGCS#2]
Após a última entrega, ao utilizar a funcionalidade "buscar endereço no mapa", o aplicativo fecha.
Percebi que apenas novos endereços adicionados estão causando esse problema. Os endereços que já estavam cadastrados não geram esse bug no sistema. Desta forma, a ausência dessa  funcionalidade compromete a usabilidade do aplicativo e precisa ser resolvida o mais rápido possível.

Suspeito que na última entrega alguma nova funcionalidade tenha afetado o salvamento de novos endereços e causado essa quebra no código. Assim, sugiro verificar como esses dados estão sendo salvos e qual parte do código é afetada gravemente a ponto de causar esse fechamento imediato da aplicação quando se busca um endereço que, aparentemente, não foi salvo no banco de dados.

**Comment by jecelen** [comment]
Obrigada por compartilhar o problema com a gente!

Podemos tentar as seguintes abordagens para descobrir o problema e resolver essa issue o mais rápido o possível:

- Primeiramente, seria bom verificar os logs de erro do sistema no momento em que o aplicativo fecha, para ver se há algum erro específico relacionado ao processamento de novos endereços.
- Como o problema parece ocorrer apenas com novos endereços, seria útil revisar as mudanças recentes no código que lidam com o salvamento de endereços no banco de dados. 
- Seria bom também realizar um processo de debugging da funcionalidade de buscar endereços no mapa. Isso pode ajudar a identificar o ponto exato onde o aplicativo falha.

Caso nenhuma alternativa funcione podemos reverter temporariamente para a versão anterior do aplicativo para comparar o comportamento das versões e entender melhor o que foi alterado.

Estou à disposição para ajudar na revisão do código e correção do problema.

**Comment by GuilhermeCupertino** [comment]
Perfeito, verifiquei a resolução e foi garantido a resolução do problema. Os dados estão conformes e os layouts também possuem congruência. Só é necessário se manter ativo a feedbacks, na busca de observar se algum novo problema será causado
