### ISSUE TITLE
Correção do Funcionamento do Login do Usuário

### ISSUE THREAD

**Issue by ghost** [GuilhermeCupertino/trabalhoGCS#25]
Desde a última atualização o login do usuário não está funcionando corretamente. Após realizar o login, a tela inicial sempre exibe "Bem vindo, TextView", indicando que as informações do usuário não estão sendo carregadas corretamente. Como resultado, funções que dependem das informações do usuário, como a de editar conta e adicionar um novo endereço não estão funcionando. 

Para solucionar esse problema será necessário fazer uma revisão do processo de login:

- Verificar a lógica de autenticação para verificar se há algum problema com a recuperação e armazenamento dos dados do usuário.
- Verificar se os dados do usuário estão sendo passados corretamente para as outras telas.

**Comment by jecelen** [comment]
Obrigada por informar esse erro pra gente! Eu e o @Gabriel-Benito conseguimos resolver.
Durante a revisão do processo de verificação de login, identifiquei que a recuperação dos dados de usuário estava comprometida então apenas os passos sugeridos aqui não funcionariam para a resolução. Seria bom acrescentar a adição de uma classe de login.

**Comment by Gabriel-Benito** [comment]
Essa issue foi encerrada de maneira conjunta. Após as correções não é mais exibido "Bem vindo, TextView" e funções que dependem das informações do usuário, como  "editar conta" e "adicionar um novo endereço" estão funcionando corretamente.
Como a @jecelen mencionou, a lógica de autenticação está correta agora e os dados sendo passados.
