### ISSUE TITLE
Correção necessária na interface de login em dispositivos específicos

### ISSUE THREAD

**Issue by jecelen** [GuilhermeCupertino/trabalhoGCS#9]
Desde a atualização para a última versão da aplicação, foi observado que a interface da tela de login não está sendo exibida corretamente em alguns dispositivos. Este problema afeta a disposição dos elementos gráficos na tela, como campos de texto, botões e mensagens de erro, comprometendo a usabilidade e a experiência do usuário. Tal fator pode dificultar o processo de autenticação dos usuários, potencialmente aumentando a taxa de desistência e afetando negativamente a primeira impressão dos usuários sobre o aplicativo.

Dispositivos onde o erro foi observado:

- Samsung s23 ultra (Android 13)
- Motorola edge 30 (Android 12)
- Motorola edge 40 (Android 13)

Considerando que a interface deve ser responsiva e adaptável a diferentes tamanhos de tela e resoluções, proponho os seguintes passos para solucionarmos essa issue: 

- avaliação e ajuste do layout das telas para melhorar a responsividade da tela de login, substituindo valores absolutos (como pixels) por valores relativos (porcentagem da tela ou de parent ocupado);
- teste em diferentes dispositivos e resoluções para assegurar a correta visualização da interface;
- podemos também considerar a implementação de uma pesquisa breve com os usuários, para coletar mais dados sobre problemas de visualização e possíveis dispositivos afetados.

**Comment by ghost** [comment]
Eu e o @GuilhermeCupertino nos dedicamos à resolução dessa issue. Realizamos ajustes no layout para melhorar a responsividade da tela de login e através de testes nos dispositivos citados confirmamos que a visualização da interface está funcionando sem problemas. Continuaremos monitorando o feedback dos usuários para garantir que não haja outros dispositivos com o mesmo problema.

**Comment by GuilhermeCupertino** [comment]
Como a @VanessaMendonca disse. Toda a resolução foi feita para que pudéssemos corrigir o problema. Garantimos a integridade dos dados. Manteremos nos atualizando sobre como será a aprovação dos usuários em relação a nova interface.
